### ISSUE TITLE
Containers restart

### ISSUE THREAD

**Issue by homlett** [humenius/traefik-certs-dumper#1]
Works pretty nicely, thanks!

Is there any chance to let it handle the restart of the containers as https://github.com/jovobe/mailcow-traefik-acme-adapter/ do?

**Comment by humenius** [comment]
This would require passing the Docker socket to the container. Needs some modification in the bash script too. I'll take a look it. :) 👍

**Comment by humenius** [comment]
Sorry for the long delay. I added the restart feature. It still has to be tested though. I'll test it ASAP. If you want, you can checkout the branch, build the branch and test it on your own. :)

**Comment by humenius** [comment]
Something that I just crossed my mind is that I have to add a check + flag if someone wants to use this functionality. The main purpose of this image is to provide a general cert dumper without completely being attached to a dependency like Mailcow.

I don't know which way I should prefer. Either way, you could for instance:
* Add an env var `MAILCOW_RESTART_CONTAINER` with either `true` or `false` as values
* Add an env var `RESTART_CONTAINERS` containing a list of container names
* Add an env var `RESTART_CONTAINERS` with a boolean value and a list of container names as arguments
* Add an optional parameter `--restart-containers=list_of_container_names`
* or leave image as is and let people fork and customize `run.sh` for their own purposes.

Maybe someone has a suggestion for handling this kind of situation?

**Comment by maximbaz** [comment]
> Add an env var RESTART_CONTAINERS containing a list of container names
> Add an optional parameter --restart-containers=list_of_container_names

I vote for one of these (don't really have a preference), it's easy to use and not dependent on anything.

I think to cleanly use this functionality, we will also need to list these containers (possibly traefik container too) in `depends_on` in docker-compose.yaml, because you don't want race conditions and this image restarting mailcow before mailcow started up.

**Comment by maximbaz** [comment]
One more point, I think we should make sure this works with https://github.com/Tecnativa/docker-socket-proxy as a more secure option, it's on my list to test this, but if you have time please feel free to try as well :)

**Comment by humenius** [comment]
> 
> 
> One more point, I think we should make sure this works with https://github.com/Tecnativa/docker-socket-proxy as a more secure option, it's on my list to test this, but if you have time please feel free to try as well :)

How does Docker socket passing work afterwards? By setting `DOCKER_HOST=tcp://localhost` in a docker-compose file or in a `docker run` command?

**Comment by maximbaz** [comment]
I'm pretty sure yes but I must test this, have only discovered this proxy recently and haven't played with it enough 🙂

**Comment by humenius** [comment]
Alright, I try to give it a test too. In case the socket responds with a 403 status code and returns an exit code ≠ 0, I expect the current method of restarting containers to work.

**Comment by maximbaz** [comment]
I tested this :) 

First of all, your image does not contain `docker` executable, [jovobe/mailcow-traefik-acme-adapter](https://github.com/jovobe/mailcow-traefik-acme-adapter) for example is based on `docker:latest` because of this reason.

Then I used this `docker-compose.yaml` as a test, and everything worked as expected with the following permissions set:

```yaml
version: "3.7"

services:
  test:
    image: jovobe/mailcow-traefik-acme-adapter
    restart: always
    entrypoint: ["bash", "/script.sh"]
    volumes:
      - ./script.sh:/script.sh
    environment:
      - DOCKER_HOST=dockersocketproxy:2375

  dockersocketproxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=1
      - ALLOW_RESTARTS=1
```

```bash
#!/bin/bash

while true; do
    echo running....
    sleep 10s
    echo "restarting: $(docker ps -qaf name=nginx-mailcow)"
    docker restart $(docker ps -qaf name=nginx-mailcow)
done
```
