### ISSUE TITLE
Container sits at Omitting...

### ISSUE THREAD

**Issue by Tuumke** [humenius/traefik-certs-dumper#27]
```[2020-11-30T12:16:06+0000]: --restart-containers is empty. Won't attempt to restart containers.
[2020-11-30T12:16:06+0000]: Got value of DOMAIN: mail.domain.tld. Splitting values.
[2020-11-30T12:16:06+0000]: Values split! Got 'mail.domain.tld'
[2020-11-30T12:16:06+0000]: Clearing dumping directory
[2020-11-30T12:16:06+0000]: Dumping certificates
[2020-11-30T12:16:06+0000]: Certificates for domain 'mail.domain.tld' don't exist. Omitting...
```

But it won't write any files? I'm trying to setup mailcow and use the certificates but, so far no luck.. 
I've already got a docker-compose stack for other stuff, which also uses the traefik_certdumper name, so in my mailcow override file, i named it with a 2

```    certdumper2:
        image: humenius/traefik-certs-dumper
        container_name: traefik_certdumper2
        network_mode: none
        volumes:
          # mount the folder which contains Traefik's `acme.json' file
          #   in this case Traefik is started from its own docker-compose in ../traefik
          #- ../traefik/data:/traefik:ro
          - /opt/docker_traefik/traefik2/acme:/traefik:ro
          # mount mailcow's SSL folder
          - /opt/docker_traefik/mailcow/data/assets/ssl:/output:rw
        environment:
          # only change this, if you're using another domain for mailcow's web frontend compared to the standard config
          - DOMAIN=${MAILCOW_HOSTNAME}
          - OVERRIDE_GID=1001
          - OVERRIDE_UID=1001
```

And the certdumper from the other stack uses:
```
  certdumper:
    container_name: traefik_certdumper
    image: humenius/traefik-certs-dumper:latest
    network_mode: none
    security_opt:
      - no-new-privileges:true
    # command: --restart-containers container1,container2,container3
    volumes:
      - $DOCKERDIR/traefik2/acme:/traefik:ro
      - $DOCKERDIR/shared/certs:/output:rw
      # - /var/run/docker.sock:/var/run/docker.sock:ro # Only needed if restarting containers (use Docker Socket Proxy instead)
    environment:
      DOMAIN: $DOMAINNAME
```

Where the domain is domain.tld. Do i need to change something here?
