### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by yashodhank** [humenius/traefik-certs-dumper#5]
Thank you so much for building and share it.. :)
Is it possible to set environment DOMAIN: with comma separated list of multiple domains?
Example:
```
# Traefik Certs Dumper - Extract LetsEncrypt Certificates - Traefik2 Compatible
  certdumper:
    container_name: traefik_certdumper
    image: humenius/traefik-certs-dumper:latest
    # command: --restart-containers container1,container2,container3
    volumes:
      - $USERDIR/docker/traefik2/acme:/traefik:ro
      - $USERDIR/docker/shared/certs:/output:rw
      # - /var/run/docker.sock:/var/run/docker.sock:ro # only needed if restarting containers
    environment:
      DOMAIN: example.com,example.org,example.net,hello.example.in
```
